import matplotlib.pyplot as plt
from estrategiaClassificação import classificação
from estrategiaRegressão import regressao

def main():
    print('\nAlgoritmo classificação baseline')
    fechamentos,riqueza = classificação('PETR3.SA', tipo =  'baseline')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_classificação_baseline.png', format='png')

    print('\nAlgoritmo classificação_sem_janela')
    fechamentos,riqueza = classificação('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_classificação_sem_janela.png', format='png')

    print('\nAlgoritmo classificação com janela de 22 dias')
    fechamentos,riqueza = classificação('PETR3.SA','1/3/2022', True, 22)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_classificação_22.png', format='png')

    print('\nAlgoritmo classificação com janela de 5 dias')
    fechamentos,riqueza = classificação('PETR3.SA','1/3/2022', True, 5)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_classificação_5.png', format='png')

    print('\nAlgoritmo classificação com janela de 1 dia')
    fechamentos,riqueza = classificação('PETR3.SA','1/3/2022', True, 1)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_classificação_1.png', format='png')

    print('\nAlgoritmo regressão baseline')
    fechamentos,riqueza = regressao('PETR3.SA', tipo =  'baseline')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_regressão_baseline.png', format='png')

    print('\nAlgoritmo regressão_sem_janela')
    fechamentos,riqueza = regressao('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_regressão_sem_janela.png', format='png')

    print('\nAlgoritmo regressão com janela de 22 dias')
    fechamentos,riqueza = regressao('PETR3.SA','1/3/2022', True, 22)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_regressão_22.png', format='png')

    print('\nAlgoritmo regressão com janela de 5 dias')
    fechamentos,riqueza = regressao('PETR3.SA','1/3/2022', True, 5)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_regressão_5.png', format='png')

    print('\nAlgoritmo regressão com janela de 1 dia')
    fechamentos,riqueza = regressao('PETR3.SA','1/3/2022', True, 1)
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_algoritmo_regressão_1.png', format='png')

if __name__ == "__main__":
    main()